### ISSUE TITLE
Is it possible to import a bit.ly export?

### ISSUE THREAD

**Issue by BrianGilbert** [LINKIWI/linkr#11]
Looking to switch to linkr, but don't want to lose all of our existing short links if possible?

**Comment by LINKIWI** [comment]
Could you elaborate on what you mean by a "bit.ly export"?

Every Linkr instance exposes a developer API; you can probably write a small script that creates new links with all your existing bit.ly short links using that endpoint.

**Comment by LINKIWI** [comment]
Closing this out as there's no actionable task
