### ISSUE TITLE
Alternative Web Servers

### ISSUE THREAD

**Issue by phonicmouse** [LINKIWI/linkr#15]
Is there any way to run this with [Caddy](https://caddyserver.com/) or Nginx?

**Comment by LINKIWI** [comment]
Yes, I would recommend running the application with [gunicorn](http://gunicorn.org/) or any other WSGI HTTP server and then reverse-proxying from the web server of your choice.

I don't have much familiarity with Caddy or nginx but you will need to translate the following Apache config:

```apache2
AliasMatch "^/(linkr/(?!.*api/).+)?$" /path/to/linkr/frontend/static/dist/index.html
Alias /linkr/static /path/to/linkr/frontend/static
```

into the appropriate configuration directives for the web server of your choice.

**Comment by itsmehemant123** [comment]
This works for me: 

```
server{
    listen 80;
    server_name <your_instance_domain>;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name <your_instance_domain>;

     location "^/(linkr/(?!.*api/).+)?$" {
          alias <your_linkr_installation_path>/frontend/static/dist/index.html;
     }

     location /linkr/static {
          alias <your_linkr_installation_path>/frontend/static;
     }

     location / {
          include uwsgi_params;
          root <your_linkr_installation_path>;
          uwsgi_pass unix:<your_linkr_installation_path>/linkr.sock;
     }

    access_log /var/log/nginx/linkr/access.log;
    error_log /var/log/nginx/linkr/error.log;

}

```

You'd have to create a service which starts the uwsgi service emitting the socket.
