### ISSUE TITLE
No redirect after successful ReCAPTCHA

### ISSUE THREAD

**Issue by tiirex9** [LINKIWI/linkr#21]
I have an instance of Linkr running on tii.blue and just tested recaptcha.

But sadly after successfully verificating my humanness, Linkr doesn't want me to visit the link behind the short link.

See https://tii.blue/test

The request of /linkr/api/link/details gives a response of 401 with the body of
``` 
{
  "failure": "failure_invalid_recaptcha", 
  "message": "ReCAPTCHA validation failed.", 
  "success": false
}
``` 

I'm not sure why this is the case.

**Comment by LINKIWI** [comment]
Hm, are you sure `recaptcha_site_key` and `recaptcha_secret_key` are set correctly?

**Comment by tiirex9** [comment]
🤦‍♂️ 

I didn't see the secret_key in secrets/server.json.
Sorry.
