### ISSUE TITLE
Demo site down

### ISSUE THREAD

**Issue by vc7ee** [LINKIWI/linkr#22]
Maybe HSTS?
![image](https://user-images.githubusercontent.com/38327267/57970330-8e76ec80-796f-11e9-88ca-6b4b76265481.png)

**Comment by LINKIWI** [comment]
I don't have the domain anymore, sorry.

**Comment by vc7ee** [comment]
Sorry, was unable to quickly launch this thing on centos, would you provide a few screenshots?
