### ISSUE TITLE
Analytic

### ISSUE THREAD

**Issue by emrahcetiner** [LINKIWI/linkr#3]
Is it planned to add analytic reporting feature?

**Comment by LINKIWI** [comment]
What functionality specifically are you looking for?

**Comment by emrahcetiner** [comment]
click/redirect count (hourly, daily, ...)
demographic (language/country)
system (brwoser, os)
etc

**Comment by LINKIWI** [comment]
This is already available in the admin interface. Granted the data is presented in its raw form, a future goal is possibly adding some sort of visualization or summary of the data.

**Comment by emrahcetiner** [comment]
How can i login as admin in demo app?

**Comment by LINKIWI** [comment]
Sorry, the admin interface is not publicly available in the demo interface because admins can view server-side secrets and delete its own account and change the admin password.

I'm closing this issue for now as there are no actionable tasks.

**Comment by LINKIWI** [comment]
Good news, I've added demo-specific server-side logic to disable some features, so the admin interface is now public in the demo interface. Please visit the [demo](https://demo.linkrapp.com) if you're interested in checking it out.
