### ISSUE TITLE
linkr_setup.py: No such file or directory: 'frontend/static/dist/bundle.js'

### ISSUE THREAD

**Issue by andreipoe** [LINKIWI/linkr#4]
Hello,

Trying to install linkr on Debian Jessie following the instructions in the readme, I get the following error when I run `linkr_setup.py`:

```
# python linkr_setup.py
Traceback (most recent call last):
  File "linkr_setup.py", line 5, in <module>
    import linkr
  File "/linkr/linkr.py", line 12, in <module>
    warm_template_cache(app)
  File "/linkr/views/__init__.py", line 22, in warm_template_cache
    frontend()
  File "/linkr/views/main.py", line 85, in frontend
    bundle = open('frontend/static/dist/bundle.js').read().decode('utf-8')
IOError: [Errno 2] No such file or directory: 'frontend/static/dist/bundle.js'
```

The `dist` directory does not exist inside `frontend/static`. I've (successfully) installed all the dependencies and followed all the installation steps. The only non-default configuration I made is changing MySQL to sqlite. 

Perhaps a step is missing in the instructions, or a required package is not listed?

**Comment by LINKIWI** [comment]
Thanks for reporting this! The instructions are actually out of order; you need to do the build step (`NODE_ENV=production npm run build`) before doing the setup. I will fix this in the documentation.

**Comment by andreipoe** [comment]
Thanks, I've tried it the other way around and it worked!
