### ISSUE TITLE
Internal Server Error when trying to shorten link

### ISSUE THREAD

**Issue by andreipoe** [LINKIWI/linkr#5]
Hello,

Running on Debian Jessie with an sqlite database, I am unable to shorten links. I get back a 500 Internal Server Error response:

```
{
  "failure": "failure_undefined", 
  "message": "There was an undefined server-side failure. This is probably a bug.", 
  "success": false
}
```

The stack trace in the web console is:

```
PUT http://my.domain/linkr/api/link/add 500 (INTERNAL SERVER ERROR) (index):10
t @ (index):10
e @ (index):9
e.(anonymous function) @ (index):10
(anonymous) @ (index):16
value @ (index):9
value @ (index):16
E @ (index):4
```

The rest of the functionality (accounts, logging in, admin panel) works as expected. 

Could this be related to using sqlite instead of mysql? Inside `config/flask.py` I have:

```
SQLALCHEMY_DATABASE_URI = 'sqlite:////data/linkr.db'
```

Thanks!

**Comment by LINKIWI** [comment]
A couple things to consider...

1. Does the absolute path `/data/linkr.db` exist?
2. Does the database reflect all the tables? If you do `sqlite3 /data/linkr.db` and run `.tables` do you see a `Link` table?
3. Can you comment out the `except` clause at the [API layer](https://github.com/LINKIWI/linkr/blob/f920a83e97e37293acbd60698ba1fdf14c800691/api/link.py#L147), restart your server, try the request again, and paste any stack traces you see?

**Comment by andreipoe** [comment]
It turns out that `/data` didn't have the proper permissions: both the folder and the database file itself had to be writable for `www-data`, as mentioned [here on StackOverflow](https://stackoverflow.com/a/21055324). Once I did `chown www-data:www-data /data/{,linkr.db}`, everything works fine.

For completeness, here is the full answer to your questions:
1. Yes.
2. There are two empty tables, `link` and `link_hit`, and the `user` table containing some data about the admin user configured through `linkr_setup.py`.
3. Here is the apache `error.log` [on PasteBin](https://pastebin.com/dYk8spFq). The main point seems to be `OperationalError: (sqlite3.OperationalError) attempt to write a readonly database`.

Thanks for the help and for your work on linkr!
